import json
import requests
import re
import sqlite3

connection = sqlite3.connect("login.db")

connection.execute("DROP TABLE if exists state")
connection.execute("CREATE TABLE state(state_id int not null, state_name text)")
connection.execute("INSERT INTO state values(?,?)",(1,  "Andaman Nicobar Islands"))
connection.execute("INSERT INTO state values(?,?)",(2,  "Andhra Pradesh"))
connection.execute("INSERT INTO state values(?,?)",(3,  "Arunachal Pradesh"))
connection.execute("INSERT INTO state values(?,?)",(4,  "Assam"))
connection.execute("INSERT INTO state values(?,?)",(5,  "Bihar"))
connection.execute("INSERT INTO state values(?,?)",(6,  "Chattisgarh"))
connection.execute("INSERT INTO state values(?,?)",(7,  "Chandigarh"))
connection.execute("INSERT INTO state values(?,?)",(8,  "Daman and Diu"))
connection.execute("INSERT INTO state values(?,?)",(9,  "Delhi"))
connection.execute("INSERT INTO state values(?,?)",(10, "Dadra and Nagar Haveli"))
connection.execute("INSERT INTO state values(?,?)",(11, "Goa"))
connection.execute("INSERT INTO state values(?,?)",(12, "Gujarat"))
connection.execute("INSERT INTO state values(?,?)",(13, "Himachal Pradesh"))
connection.execute("INSERT INTO state values(?,?)",(14, "Haryana"))
connection.execute("INSERT INTO state values(?,?)",(15, "Jharkhand"))
connection.execute("INSERT INTO state values(?,?)",(16, "Jammu & Kashmir"))
connection.execute("INSERT INTO state values(?,?)",(17, "Karnataka"))
connection.execute("INSERT INTO state values(?,?)",(18, "Kerala"))
connection.execute("INSERT INTO state values(?,?)",(19, "Lakshadweep"))
connection.execute("INSERT INTO state values(?,?)",(20, "Maharashtra"))
connection.execute("INSERT INTO state values(?,?)",(21, "Meghalaya"))
connection.execute("INSERT INTO state values(?,?)",(22, "Manipur"))
connection.execute("INSERT INTO state values(?,?)",(23, "Madhya Pradesh"))
connection.execute("INSERT INTO state values(?,?)",(24, "Mizoram"))
connection.execute("INSERT INTO state values(?,?)",(25, "Nagaland"))
connection.execute("INSERT INTO state values(?,?)",(26, "Orissa"))
connection.execute("INSERT INTO state values(?,?)",(27, "Punjab"))
connection.execute("INSERT INTO state values(?,?)",(28, "Pondicherry"))
connection.execute("INSERT INTO state values(?,?)",(29, "Rajasthan"))
connection.execute("INSERT INTO state values(?,?)",(30, "Tamil Nadu"))
connection.execute("INSERT INTO state values(?,?)",(31, "Telangana"))
connection.execute("INSERT INTO state values(?,?)",(32, "Tripura"))
connection.execute("INSERT INTO state values(?,?)",(33, "Uttarakhand"))
connection.execute("INSERT INTO state values(?,?)",(34, "Uttar Pradesh"))
connection.execute("INSERT INTO state values(?,?)",(35, "West Bengal"))
connection.execute("INSERT INTO state values(?,?)",(36, "Sikkim"))

connection.commit()
connection.close()

print("Done inserting State records!!")